[package]
name = "rag-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.80"
langchain-rust = { version= "4.1.2", features=["sqlite"]}
llama_cpp = {version="0.3.2", features=["metal"]}
serde_json = "1.0.117"
futures-util = "0.3.30"
colored = "2.1.0"
